import img from "../images/products/producto.jpg";
import ingredientes from "./ingredientes";

const productos = [
  {
    id: 1,
    nombre: "Jugos Verdes",
    productos: [
      {
        nombre: "Día Verde",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.espinacas,
          ingredientes.perejil,
          ingredientes.apio,
          ingredientes.manzana,
          ingredientes.limon,
        ],
        beneficios: [
          "Alcaliniza",
          "Diurético",
          "Hidratante",
          "Rico en vitamina C",
          "Mejora la digestión",
        ],
      },
      {
        nombre: "Detox",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.acelga,
          ingredientes.apio,
          ingredientes.pepino,
          ingredientes.pera,
          ingredientes.limon,
        ],
        beneficios: [
          "Diurético",
          "Elimina toxinas",
          "Regula niveles de colesterol",
          "Mejora el aspecto en piel",
        ],
      },
      {
        nombre: "Fresco intenso",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.espinacas,
          ingredientes.pepino,
          ingredientes.jengibre,
          ingredientes.piña,
          ingredientes.aguaCoco,
        ],
        beneficios: [
          "Hidrata y repone vitaminas",
          "Nutre la piel",
          "Diurético",
          "Analgésico natural",
        ],
      },
      {
        nombre: "Digestivo",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.perejil,
          ingredientes.apio,
          ingredientes.pepino,
          ingredientes.limon,
          ingredientes.naranja,
        ],
        beneficios: [
          "Mejora la digestión",
          "Elimina toxinas",
          "Regula la presión arterial",
          "Reduce el colesterol",
        ],
      },
      {
        nombre: "Verde Vigor",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.espinacas,
          ingredientes.zanahoria,
          ingredientes.apio,
          ingredientes.pepino,
          ingredientes.manzana,
        ],
        beneficios: [
          "Depurativo",
          "Repone vitaminas",
          "Ayuda a aumentar la fuerza muscular",
          "Retrasa el envejecimiento celular",
        ],
      },
      {
        nombre: "Reductor",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.perejil,
          ingredientes.apio,
          ingredientes.toronja,
          ingredientes.piña,
        ],
        beneficios: [
          "Acelera el metabolismo",
          "Elimina toxinas",
          "Diurético",
          "Combate la celulitis",
        ],
      },
      {
        nombre: "Depurativo",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.apio,
          ingredientes.pepino,
          ingredientes.pimientaCayena,
          ingredientes.piña,
        ],
        beneficios: ["Adelgazante", "Libera impurezas retenidas", "Diurética"],
      },
    ],
  },
  {
    id: 2,
    nombre: "Jugos de Raiz",
    productos: [
      {
        nombre: "Bloody Mary",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.betabel,
          ingredientes.apio,
          ingredientes.jengibre,
          ingredientes.manzana,
          ingredientes.limon,
        ],
        beneficios: [
          "Antioxidante",
          "Diurético",
          "Evita el estreñimiento",
          "Regula el metabolismo",
          "Rejuvenece la piel",
        ],
      },
      {
        nombre: "Super Inmune",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.betabel,
          ingredientes.curcuma,
          ingredientes.zanahoria,
          ingredientes.naranja,
        ],
        beneficios: [
          "Aumenta tus defensas",
          "Purifica la sangre",
          "Desintoxica",
          "Antioxidante",
        ],
      },
      {
        nombre: "Coco Detox",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.jengibre,
          ingredientes.curcuma,
          ingredientes.piña,
          ingredientes.aguaCoco,
        ],
        beneficios: [
          "Hidratante",
          "Diurético",
          "Elimina la acidez",
          "Antiinflamatorio",
        ],
      },
    ],
  },
  {
    id: 3,
    nombre: "Shots de Jengibre",
    productos: [
      {
        nombre: "Shot Jengibre, piña",
        precio: 60,
        imagen: img,
        ingredientes: [ingredientes.jengibre, ingredientes.piña],
        beneficios: [
          "Elimina líquidos retenidos",
          "Antiinflamatorio",
          "Mejora la digestión",
          "Previene ulceras gástricas",
        ],
      },
      {
        nombre: "Shot jengibre, Cúrcuma, naranja",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.jengibre,
          ingredientes.curcuma,
          ingredientes.naranja,
        ],
        beneficios: [
          "Refuerza el sistema inmunológico",
          "Antigripal",
          "Antiviral",
          "Antiinflamatorio",
        ],
      },
      {
        nombre: "Shot Jengibre, Canela, Manzana",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.jengibre,
          ingredientes.canela,
          ingredientes.manzana,
        ],
        beneficios: [
          "Alcaliniza",
          "Promueve la quema de grasa",
          "Reduce niveles de glucosa en sangre",
          "Desinflama",
        ],
      },
      {
        nombre: "Shot Jengibre, Limón, Zanahoria",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.jengibre,
          ingredientes.limon,
          ingredientes.zanahoria,
        ],
        beneficios: [
          "Mejora el aspecto de piel",
          "Antioxidante",
          "Elimina líquidos retenidos",
          "Propiedades anticancerígenas",
        ],
      },
    ],
  },
  {
    id: 4,
    nombre: "Smothies",
    productos: [
      {
        nombre: "Frutos Rojos",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheCoco,
          ingredientes.espinacas,
          ingredientes.moras,
          ingredientes.mielAbeja,
        ],
        beneficios: ["Antioxidante", "Regula la digestión", "Depura toxinas"],
      },
      {
        nombre: "Energetico",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.avena,
          ingredientes.espinacas,
          ingredientes.manzana,
          ingredientes.platano,
        ],
        beneficios: [
          "Provee energía estable",
          "Limpia el organismo",
          "Aumenta fuerza muscular",
        ],
      },
      {
        nombre: "Del Tropico",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheCoco,
          ingredientes.piña,
          ingredientes.platano,
          ingredientes.mango,
        ],
        beneficios: [
          "Rico en hierro",
          "Reduce niveles de hipertensión",
          "Mejora aspecto de piel",
        ],
      },
      {
        nombre: "Chocolate Skinny",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheCoco,
          ingredientes.espinacas,
          ingredientes.cocoa,
          ingredientes.linaza,
          ingredientes.platano,
          ingredientes.mielAbeja,
        ],
        beneficios: [
          "Fortalece tus huesos",
          "Reduce el estrés y mejora el animo",
          "Controla tu peso",
        ],
      },
      {
        nombre: "Morafresh",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheAlmendras,
          ingredientes.zarzamoras,
          ingredientes.piña,
          ingredientes.platano,
        ],
        beneficios: [
          "Antioxidante",
          "Elimina líquidos retenidos",
          "Bajo en calorías",
          "Regula la digestión",
        ],
      },
      {
        nombre: "Manzana-Canela",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheAlmendras,
          ingredientes.cacahuate,
          ingredientes.canela,
          ingredientes.manzana,
          ingredientes.platano,
        ],
        beneficios: [
          "Alto contenido en fibra",
          "Mejora la digestión",
          "Antihipertensivo",
          "Ayuda a reducir el colesterol",
        ],
      },
      {
        nombre: "Super Fresa",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheAlmendras,
          ingredientes.semillasHemp,
          ingredientes.fresas,
          ingredientes.vainilla,
          ingredientes.aceiteCoco,
          ingredientes.mielAbeja,
        ],
        beneficios: [
          "Antioxidante",
          "Antiviral",
          "Antiinflamatorio",
          "Efecto diurético",
        ],
      },
      {
        nombre: "Corazón Contento",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.avena,
          ingredientes.canela,
          ingredientes.manzana,
          ingredientes.fresas,
          ingredientes.mielAbeja,
        ],
        beneficios: [
          "Disminuye el colesterol",
          "Antioxidante",
          "Protege las arterias",
          "Regula la función intestinal",
          "Combate el estreñimiento",
        ],
      },
    ],
  },
  {
    id: 5,
    nombre: "Leches Vegetales",
    productos: [
      {
        nombre: "Leche de Almendras",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.almendras,
          ingredientes.canela,
          ingredientes.vainilla,
          ingredientes.sal,
          ingredientes.datiles,
          ingredientes.aguaAlcalina,
        ],
        beneficios: [
          "Libre de lactosa",
          "No contiene gluten ni colesterol",
          "Alto contenido en calcio y fibra",
          "Baja en calorías",
          "Mejora la digestión",
        ],
      },
      {
        nombre: "Leche de Coco",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.pulpaCoco,
          ingredientes.aguaCoco,
          ingredientes.ralladuraLimon,
          ingredientes.mielAbeja,
        ],
        beneficios: [
          "Antibiótico natural",
          "Reduce el colesterol",
          "Combate infecciones virales",
          "Protege las arterias",
          "Favorece la perdida de peso",
        ],
      },
      {
        nombre: "Leche Dorada",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.lecheCoco,
          ingredientes.curcuma,
          ingredientes.pimientaNegra,
          ingredientes.canela,
          ingredientes.mielAbeja,
        ],
        beneficios: [
          "Mejora la salud digestiva",
          "Fortalece las defensas",
          "Antiinflamatoria",
          "Antioxidante",
        ],
      },
    ],
  },
  {
    id: 6,
    nombre: "Bebidas Adicionales",
    productos: [
      {
        nombre: "Aloe Vera",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.pulpaAloe,
          ingredientes.chia,
          ingredientes.limon,
          ingredientes.mielAbeja,
          ingredientes.aguaAlcalina,
        ],
        beneficios: [
          "Desinfectante",
          "Cicatrizante",
          "Antiinflamatorio",
          "Desintoxicante",
          "Suavizante intestinal",
        ],
      },
      {
        nombre: "Agua de Coco",
        precio: 60,
        imagen: img,
        ingredientes: [ingredientes.aguaCoco],
        beneficios: ["Hidratante", "Depurativa"],
      },
      {
        nombre: "Kombucha",
        precio: 60,
        imagen: img,
        ingredientes: [ingredientes.teNegro],
        beneficios: [
          "Bebida pro biótica",
          "Refuerza el sistema inmunológico",
          "Mejora la digestión",
          "Controla la acidez estomacal",
          "Gran poder detox",
        ],
      },
      {
        nombre: "Agua Alcalina con Clorofila",
        precio: 60,
        imagen: img,
        ingredientes: [],
        beneficios: [
          "Desintoxicante",
          "Antioxidante",
          "Purificante",
          "Mejora tu sistema inmunológico",
        ],
      },
      {
        nombre: "Limonada Activada",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.carbonActivado,
          ingredientes.limon,
          ingredientes.estevia,
          ingredientes.aguaAlcalina,
        ],
        beneficios: [
          "Aumenta tus defensas",
          "Neutraliza y elimina toxinas de metales pesados",
          "Alcalinizante",
          "Regula transito intestinal y disminuye gases",
          "Desinfecta boca y garganta",
        ],
      },
      {
        nombre: "Limonada Antigripal",
        precio: 60,
        imagen: img,
        ingredientes: [
          ingredientes.limon,
          ingredientes.naranja,
          ingredientes.ajo,
          ingredientes.jengibre,
          ingredientes.pimientaCayena,
          ingredientes.mielAbeja,
        ],
        beneficios: ["Antiviral", "Inmunoestimulante"],
      },
    ],
  },
];

export default productos;
